spring:
  application:
    name: <SERVICE_NAME>

server:
  port: <SERVICE_PORT>

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: /actuator
  endpoint:
    health:
      show-details: <HEALTH_DETAILS_SETTING>
      show-components: <HEALTH_COMPONENTS_SETTING>
